# Generated by Django 2.2.6 on 2020-03-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('early_review', '0016_authuser_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='private_key',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='public_key',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
