# Generated by Django 2.2.6 on 2020-04-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('early_review', '0018_encryptioninfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptioninfo',
            name='secret_key_encrypted',
            field=models.BinaryField(max_length=10000),
        ),
    ]
