# Generated by Django 2.2.6 on 2020-04-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('early_review', '0020_auto_20200412_1545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EncryptionInfo',
        ),
    ]
