# Generated by Django 2.2.6 on 2020-04-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('early_review', '0023_signedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signedfile',
            name='secret_key_encrypted',
        ),
    ]
