# Generated by Django 2.2.6 on 2020-04-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('early_review', '0024_remove_signedfile_secret_key_encrypted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signedfile',
            name='encrypted_file_name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='signedfile',
            name='signed_file_name',
            field=models.TextField(max_length=200),
        ),
    ]
