# Generated by Django 2.2.6 on 2020-04-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('early_review', '0025_auto_20200414_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptioninfo',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='signedfile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
