# Generated by Django 2.2.6 on 2020-04-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('early_review', '0027_authuser_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptioninfo',
            name='secret_key_encrypted',
            field=models.TextField(max_length=128),
        ),
    ]
